### ISSUE TITLE
ubuntu 20

### ISSUE THREAD

**Issue by xoroz** [bootc/nrpe-ng#4]
i am unable to use it under ubuntu 20
the error is
root@ubuntu20template:~/git/linux-nagios-plugin# /usr/sbin/nrpe -c /etc/nrpe.cfg -f 
Traceback (most recent call last):
  File "/usr/sbin/nrpe", line 11, in <module>
    load_entry_point('nrpe-ng==0.2.0', 'console_scripts', 'nrpe-ng')()
  File "/usr/lib/python3/dist-packages/nrpe_ng/server/__init__.py", line 22, in main
    return Server().run()
  File "/usr/lib/python3/dist-packages/nrpe_ng/server/server.py", line 231, in run
    self.reload_config()
  File "/usr/lib/python3/dist-packages/nrpe_ng/server/server.py", line 104, in reload_config
    raise ConfigError(
TypeError: __init__() missing 1 required positional argument: 'exception'

My /etc/nrpe.cfg is:

log_facility=daemon
pid_file=/var/run/nagios/nrpe.pid
log_file=/usr/lib/nagios/nrpe.log
debug=0
server_port=6699
listen_queue_size=5
nrpe_user=nrpe
nrpe_group=nrpe
allowed_hosts=10.255.8.185,10.255.8.234,10.255.8.236
dont_blame_nrpe=1
allow_bash_command_substitution=1
command_timeout=50
connection_timeout=300
ssl_logging=0x01
ssl_cacert_file=/etc/ssl/nrpe/ca_cert.pem
ssl_cert_file=/etc/ssl/nrpe/client_cert.pem
ssl_privatekey_file=/etc/ssl/nrpe/client_cert.key
ssl_client_certs=2

include_dir=/etc/nrpe.d/

**Comment by russellvt** [comment]
Looks like you are using `nrpe` rather than `nrpe-ng` here?

**Comment by russellvt** [comment]
This is `nrpe` ... not `nrpe-ng` (two different animals).

This should be closed.
